import { Inter } from 'next/font/google'

import './globals.css'
import AdminPanel from '~/components/admin-panel'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next CMS App',
  description: 'Generated by next-cms',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <AdminPanel />
      </body>
    </html>
  )
}
