export const metadata = {
  title: 'Create Next CMS App',
  description: 'Generated by next-cms',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
